from scrapers.mma_scraper import scrape_bellator_events, scrape_ufc_events, scrape_one_events
from scrapers.boxing_scraper import scrape_wbc_events, scrape_wba_events, scrape_ibf_events, scrape_wbo_events
from scrapers.bjj_scraper import scrape_ibjjf_events, scrape_adcc_events
from scrapers.muaythai_scraper import scrape_lf_events, scrape_mmt_events, scrape_tf_events
from scrapers.judo_scraper import scrape_usajudo_events